services:
  mongo:
    image: mongo:7.0
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: python-app
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: secret
      MONGO_DB: mydatabase
    command: python init_data.py

volumes:
  mongo-data: